import Head from "next/head";
import { useRouter } from "next/router";
import { useCurrentUser } from "../src/hooks/auth/useCurrentUser";
import { useLogout } from "../src/hooks/auth/useLogout";

export default function Profile() {
  const { user: currentUser } = useCurrentUser();
  const { logout } = useLogout();
  const router = useRouter();

  return (
    <>
      <Head>
        <title>kargakarga | profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-screen h-screen flex flex-col items-center justify-center">
        <p className="font-bold text-2xl">Welcome back</p>
        <div className="font-semibold">
          You are: {currentUser?.data.fullName}
        </div>

        <button
          onClick={() => {
            logout();
            router.push("/login");
          }}
          className="mt-2 border border-solid border-black py-2 px-4 rounded cursor-pointer"
        >
          Logout
        </button>
        <button
          className="mt-2 border border-solid border-black py-2 px-4 rounded cursor-pointer"
          onClick={() => router.push("/dashboard")}
        >
          Dashboard
        </button>
      </div>
    </>
  );
}
